### ISSUE TITLE
Map does not resize properly on IE11

### ISSUE THREAD

**Issue by TimFau** [clarketm/image-map#10]
Thanks for the plugin! It's been very helpful. One issue I found is that it does not seem to resize properly for IE11.

1. In IE11, go to: https://www.travismclarke.com/imagemap/
2. Resize window to about 800px wide
3. Click on "Orange" shape & see that "Pink" is selected
4. Also try clicking on top left corner of "Yellow shape" & see blue is selected

**Comment by clarketm** [comment]
🤔 let me see if this can be polyfilled in the build process.

**Comment by clarketm** [comment]
@TimFau 
I made a few tweaks to the bundle to resolve issues with IE 9, 10, 11.
1. Remove usage on `Symbol` as it is unknown to IE (babel/babel#7597)
2. Bypass image cache for `img` *load* event (e.g. https://davidwalsh.name/image-load-event).

[v1.1.7](https://github.com/clarketm/image-map/tree/v1.1.7) contains the fixes.
