### ISSUE TITLE
A little help on debugging (if possible)

### ISSUE THREAD

**Issue by richardjonesnz** [clarketm/image-map#2]
Loving the concept and implements OK (coordinates changing with window size as expected).  Unfortunately it's not honouring the href tag and providing a link.  No errors in the console.  Stumped.

Any ideas much appreciated.

**Comment by clarketm** [comment]
@richardjonesnz – I have not had any issues, personally, using `href` and `onclick` when dealing with conditional logic on click. Could you provide an example of the errant code to assist with debugging?

**Comment by richardjonesnz** [comment]
Hey, thanks for getting back to me, and so quickly.  You will see I still have redundant files in here since I basically cloned your repo and subbed your map/image with mine.

[mapdemo.zip](https://github.com/clarketm/image-map/files/1633284/mapdemo.zip)

**Comment by clarketm** [comment]
@richardjonesnz – no worries, I do the same thing all the time! Regarding, the issue you are experiencing, it would appear that the initial `coords` that you are using in the `<area>` tag are incorrect for the dimensions of the original image. It is true that `image-map` with dynamically update these values on resize, but the **initial** values for `coords` should still correlate with the original image.

I would suggest uploading the original image to https://www.image-map.net/ to simplify the creating of the image map shapes themselves. I just tested it on your project and it works like a charm.

**Comment by richardjonesnz** [comment]
OK thanks a lot for your time, I will do that.  Good to know it works!

**Comment by clarketm** [comment]
@richardjonesnz – let me know if this doesn't work for you. I didn't know exactly what boundaries you wanted for the image map shapes, so in my test I used `coords="1412,842,255,71"` to effectively target the upper left sub-image. The image map generator I linked should allow you to reproduce in not time!
