### ISSUE TITLE
How to use in Nuxt.js app.

### ISSUE THREAD

**Issue by dokechin** [clarketm/image-map#6]
I want to use image-map plugin in Nuxt.js app.

So I make sample app
https://github.com/dokechin/nuxt-imagemap-example

In the case, image-map page visit second time from nuxt-link.
It not going successfully. (http://localhost:3000/)

In the case image-map page visited at first.
It  going successfully.(http://localhost:3000/index2)

How to execute former case?

**Comment by clarketm** [comment]
@dokechin - this does not appear to be an issue with [ImageMap](https://github.com/clarketm/image-map) but rather an issue in implementation. I am not a Vue user personally, but I did observe, after looking at the Vue [lifecycle diagram](https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram), that with your app if you replace `mounted` with `created` in [index.vue](https://github.com/dokechin/nuxt-imagemap-example/blob/master/pages/test/index.vue#L14) then it works as expected.

**e.g.**

```diff
-  mounted() {
+  created() {
    $('img[usemap]').imageMap()
  }
```

**Comment by dokechin** [comment]
Very very thanks you, I can do!!
